name: qpa
version: "1.36"
license: "GPL-2.0-or-later"
date: 2025-04-07
description: |
    Quivers and Path Algebras

authors:
    - name: Edward Green
      url: http://www.math.vt.edu/people/green
    - name: Oeyvind Solberg
      url: https://folk.ntnu.no/oyvinso/

maintainers:
    - name: Edward Green
      url: http://www.math.vt.edu/people/green
    - name: Oeyvind Solberg
      url: https://folk.ntnu.no/oyvinso/

GAP: ">=4.5"

needed-pkgs:
    - name: "GBNP"
      version: ">=0.9.5"
      url: "https://gap-packages.github.io/gbnp/"

www: https://gap-packages.github.io/qpa
readme: README
packageinfo: https://gap-packages.github.io/qpa/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/qpa/releases/download/v1.36/qpa-1.36.tar.gz

abstract: |
    The <span class="pkgname">QPA</span> package provides data structures                    and algorithms for doing computations with finite dimensional quotients                    of path algebras, and finitely generated modules over such algebras. The                    current version of the QPA package has data structures for quivers,                    quotients of path algebras, and modules, homomorphisms and complexes of                    modules over quotients of path algebras.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    quiver, path algebra.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GS25</span>]   <b class='BibAuthor'>Green, E. and Solberg, O.</b>,
     <i class='BibTitle'>qpa, Quivers and Path Algebras,
             Version 1.36</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/qpa">https://gap-packages.github.io/qpa</a></span>.
    </p>
    

bibtex: |
    @misc{ qpa,
      author =           {Green, E. and Solberg, O.},
      title =            {{qpa}, {Quivers and Path Algebras}, {V}ersion 1.36},
      month =            {Apr},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href                                                         {https://gap-packages.github.io/qpa}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary {}{}{}\texttt{qpa}}},
      keywords =         {quiver; path algebra},
      printedkey =       {GS25}
    }

