DeclareGlobalFunction( "computeLPSarray" );
DeclareGlobalFunction( "SourceOfArrow" );
DeclareGlobalFunction( "TargetOfArrow" );
DeclareGlobalFunction( "CyclicPermutationOfABand" );
DeclareGlobalFunction( "MaximumLengthOfDirectString" );
DeclareGlobalFunction( "NumberOfJoints" );
DeclareOperation("IsABand", [ IsAlgebra, IsString ]);
DeclareOperation("StringsLessThan", [ IsAlgebra, IsPosInt ]);
DeclareOperation("BandsLessThan", [ IsAlgebra, IsPosInt ]);
DeclareOperation("BandRepresentativesLessThan", [ IsAlgebra, IsPosInt ]);
DeclareOperation("IsDomesticStringAlgebra", [ IsAlgebra ]);
DeclareOperation("BridgeQuiver", [ IsAlgebra ]);
