DeclareOperation( "IsSelfinjective", [IsSubalgebraFpPathAlgebra ] ); 
DeclareOperation( "LoewyLength", [IsPathAlgebraMatModule ] ); 
DeclareOperation( "CoxeterPolynomial", [IsPathAlgebra ] ); 
DeclareOperation( "CoxeterMatrix", [IsPathAlgebra ] ); 
DeclareOperation( "RadicalSeries", [IsPathAlgebraMatModule ] ); 
DeclareOperation( "SocleSeries", [IsPathAlgebraMatModule ] ); 
DeclareOperation( "DimensionMatModule", [IsPathAlgebraMatModule ] ); 
DeclareOperation( "IsProjectiveModule", [IsPathAlgebraMatModule ] ); 
DeclareOperation( "IsInjectiveModule", [IsPathAlgebraMatModule ] ); 
DeclareOperation( "IsSimpleModule", [IsPathAlgebraMatModule ] ); 
DeclareOperation( "IsSemisimpleModule", [IsPathAlgebraMatModule ] );
DeclareOperation( "1st_Syzygy", [IsPathAlgebraMatModule ] );
DeclareOperation( "nth_Syzygy", [IsPathAlgebraMatModule, IS_INT ] );
DeclareOperation( "TipMonomialandCoefficientOfVector", [ IsAlgebra, IsCollection ] );
DeclareOperation( "TipReduceVectors", [ IsAlgebra, IsCollection ] );
DeclareOperation( "CoefficientsOfVectors", [ IsAlgebra, IsCollection, IsList ] );